(***********************************************************************)
(*                                                                     *)
(*                   OCaml interface to Sundials                       *)
(*                                                                     *)
(*  Timothy Bourke (Inria), Jun Inoue (Inria), and Marc Pouzet (LIENS) *)
(*                                                                     *)
(*  Copyright 2018 Institut National de Recherche en Informatique et   *)
(*  en Automatique.  All rights reserved.  This file is distributed    *)
(*  under a New BSD License, refer to the file LICENSE.                *)
(*                                                                     *)
(***********************************************************************)

exception NotImplementedBySundialsVersion

(* Re-export constants generated by configure.  *)
let version = Sundials_configuration.version
let sundials_version = Sundials_configuration.sundials_version
let lapack_enabled = Sundials_configuration.lapack_enabled
let mpi_enabled = Sundials_configuration.mpi_enabled
let klu_enabled = Sundials_configuration.klu_enabled
let superlumt_enabled = Sundials_configuration.superlumt_enabled
let nvecpthreads_enabled = Sundials_configuration.nvecpthreads_enabled
let nvecopenmp_enabled = Sundials_configuration.nvecopenmp_enabled
let monitoring_enabled = Sundials_configuration.monitoring_enabled

(* Let C code know about some of the values in this module, and obtain
   a few parameters from the C side.  *)

external c_get_constants
  : unit -> float * float * float = "sunml_sundials_get_constants"

let big_real, small_real, unit_roundoff = c_get_constants ()

