(***********************************************************************)
(*                                                                     *)
(*                   OCaml interface to Sundials                       *)
(*                                                                     *)
(*  Timothy Bourke (Inria), Jun Inoue (Inria), and Marc Pouzet (LIENS) *)
(*                                                                     *)
(*  Copyright 2018 Institut National de Recherche en Informatique et   *)
(*  en Automatique.  All rights reserved.  This file is distributed    *)
(*  under a New BSD License, refer to the file LICENSE.                *)
(*                                                                     *)
(***********************************************************************)

exception NotImplementedBySundialsVersion

(* Re-export constants generated by configure.  *)
let version = Sundials_configuration.version
let sundials_version = Sundials_configuration.sundials_version
let lapack_enabled = Sundials_configuration.lapack_enabled
let mpi_enabled = Sundials_configuration.mpi_enabled
let klu_enabled = Sundials_configuration.klu_enabled
let superlumt_enabled = Sundials_configuration.superlumt_enabled
let nvecpthreads_enabled = Sundials_configuration.nvecpthreads_enabled
let nvecopenmp_enabled = Sundials_configuration.nvecopenmp_enabled
let monitoring_enabled = Sundials_configuration.monitoring_enabled

(* Let C code know about some of the values in this module, and obtain
   a few parameters from the C side.  *)

external c_get_constants
  : unit -> float * float * float * int = "sunml_sundials_get_constants"

let big_real, small_real, unit_roundoff, stdc_version = c_get_constants ()

(* synchronized with sundials_ml.h: sundials_version_number_index *)
type [@warning "-69"] sundials_version_number = {
      major : int;
      minor : int;
      patch : int;
      label : string;
  }

external c_get_version_number : unit -> sundials_version_number option
  = "sunml_sundials_get_version_number"

let _ =
  (* Sundials version at compilation *)
  let cmajor, cminor, cpatch, _ = version in
  (* Sundials version at runtime *)
  match c_get_version_number () with
  | Some { major; minor; patch; _ } when major <> cmajor || minor <> cminor ->
      failwith (Printf.sprintf
        "Sundials/ML was compiled for Sundials %d.%d.%d but Sundials %d.%d.%d is installed."
        cmajor cminor cpatch
         major  minor  patch)
  | _ -> ()

